CITIES_DATA = [
    "Insert into cities (code, name) values ('4200051','Abdon Batista');",
    "Insert into cities (code, name) values ('4200101','Abelardo Luz');",
    "Insert into cities (code, name) values ('4200200','Agrolândia');",
    "Insert into cities (code, name) values ('4200309','Agronômica');",
    "Insert into cities (code, name) values ('4200408','Água Doce');",
    "Insert into cities (code, name) values ('4200507','Águas de Chapecó');",
    "Insert into cities (code, name) values ('4200556','Águas Frias');",
    "Insert into cities (code, name) values ('4200606','Águas Mornas');",
    "Insert into cities (code, name) values ('4200705','Alfredo Wagner');",
    "Insert into cities (code, name) values ('4200754','Alto Bela Vista');",
    "Insert into cities (code, name) values ('4200804','Anchieta');",
    "Insert into cities (code, name) values ('4200903','Angelina');",
    "Insert into cities (code, name) values ('4201000','Anita Garibaldi');",
    "Insert into cities (code, name) values ('4201109','Anitápolis');",
    "Insert into cities (code, name) values ('4201208','Antônio Carlos');",
    "Insert into cities (code, name) values ('4201257','Apiúna');",
    "Insert into cities (code, name) values ('4201273','Arabutã');",
    "Insert into cities (code, name) values ('4201307','Araquari');",
    "Insert into cities (code, name) values ('4201406','Araranguá');",
    "Insert into cities (code, name) values ('4201505','Armazém');",
    "Insert into cities (code, name) values ('4201604','Arroio Trinta');",
    "Insert into cities (code, name) values ('4201653','Arvoredo');",
    "Insert into cities (code, name) values ('4201703','Ascurra');",
    "Insert into cities (code, name) values ('4201802','Atalanta');",
    "Insert into cities (code, name) values ('4201901','Aurora');",
    "Insert into cities (code, name) values ('4201950','Balneário Arroio do Silva');",
    "Insert into cities (code, name) values ('4202008','Balneário Camboriú');",
    "Insert into cities (code, name) values ('4202057','Balneário Barra do Sul');",
    "Insert into cities (code, name) values ('4202073','Balneário Gaivota');",
    "Insert into cities (code, name) values ('4202081','Bandeirante');",
    "Insert into cities (code, name) values ('4202099','Barra Bonita');",
    "Insert into cities (code, name) values ('4202107','Barra Velha');",
    "Insert into cities (code, name) values ('4202131','Bela Vista do Toldo');",
    "Insert into cities (code, name) values ('4202156','Belmonte');",
    "Insert into cities (code, name) values ('4202206','Benedito Novo');",
    "Insert into cities (code, name) values ('4202305','Biguaçu');",
    "Insert into cities (code, name) values ('4202404','Blumenau');",
    "Insert into cities (code, name) values ('4202438','Bocaina do Sul');",
    "Insert into cities (code, name) values ('4202453','Bombinhas');",
    "Insert into cities (code, name) values ('4202503','Bom Jardim da Serra');",
    "Insert into cities (code, name) values ('4202537','Bom Jesus');",
    "Insert into cities (code, name) values ('4202578','Bom Jesus do Oeste');",
    "Insert into cities (code, name) values ('4202602','Bom Retiro');",
    "Insert into cities (code, name) values ('4202701','Botuverá');",
    "Insert into cities (code, name) values ('4202800','Braço do Norte');",
    "Insert into cities (code, name) values ('4202859','Braço do Trombudo');",
    "Insert into cities (code, name) values ('4202875','Brunópolis');",
    "Insert into cities (code, name) values ('4202909','Brusque');",
    "Insert into cities (code, name) values ('4203006','Caçador');",
    "Insert into cities (code, name) values ('4203105','Caibi');",
    "Insert into cities (code, name) values ('4203154','Calmon');",
    "Insert into cities (code, name) values ('4203204','Camboriú');",
    "Insert into cities (code, name) values ('4203253','Capão Alto');",
    "Insert into cities (code, name) values ('4203303','Campo Alegre');",
    "Insert into cities (code, name) values ('4203402','Campo Belo do Sul');",
    "Insert into cities (code, name) values ('4203501','Campo Erê');",
    "Insert into cities (code, name) values ('4203600','Campos Novos');",
    "Insert into cities (code, name) values ('4203709','Canelinha');",
    "Insert into cities (code, name) values ('4203808','Canoinhas');",
    "Insert into cities (code, name) values ('4203907','Capinzal');",
    "Insert into cities (code, name) values ('4203956','Capivari de Baixo');",
    "Insert into cities (code, name) values ('4204004','Catanduvas');",
    "Insert into cities (code, name) values ('4204103','Caxambu do Sul');",
    "Insert into cities (code, name) values ('4204152','Celso Ramos');",
    "Insert into cities (code, name) values ('4204178','Cerro Negro');",
    "Insert into cities (code, name) values ('4204194','Chapadão do Lageado');",
    "Insert into cities (code, name) values ('4204202','Chapecó');",
    "Insert into cities (code, name) values ('4204251','Cocal do Sul');",
    "Insert into cities (code, name) values ('4204301','Concórdia');",
    "Insert into cities (code, name) values ('4204350','Cordilheira Alta');",
    "Insert into cities (code, name) values ('4204400','Coronel Freitas');",
    "Insert into cities (code, name) values ('4204459','Coronel Martins');",
    "Insert into cities (code, name) values ('4204509','Corupá');",
    "Insert into cities (code, name) values ('4204558','Correia Pinto');",
    "Insert into cities (code, name) values ('4204608','Criciúma');",
    "Insert into cities (code, name) values ('4204707','Cunha Porã');",
    "Insert into cities (code, name) values ('4204756','Cunhataí');",
    "Insert into cities (code, name) values ('4204806','Curitibanos');",
    "Insert into cities (code, name) values ('4204905','Descanso');",
    "Insert into cities (code, name) values ('4205001','Dionísio Cerqueira');",
    "Insert into cities (code, name) values ('4205100','Dona Emma');",
    "Insert into cities (code, name) values ('4205159','Doutor Pedrinho');",
    "Insert into cities (code, name) values ('4205175','Entre Rios');",
    "Insert into cities (code, name) values ('4205191','Ermo');",
    "Insert into cities (code, name) values ('4205209','Erval Velho');",
    "Insert into cities (code, name) values ('4205308','Faxinal dos Guedes');",
    "Insert into cities (code, name) values ('4205357','Flor do Sertão');",
    "Insert into cities (code, name) values ('4205407','Florianópolis');",
    "Insert into cities (code, name) values ('4205431','Formosa do Sul');",
    "Insert into cities (code, name) values ('4205456','Forquilhinha');",
    "Insert into cities (code, name) values ('4205506','Fraiburgo');",
    "Insert into cities (code, name) values ('4205555','Frei Rogério');",
    "Insert into cities (code, name) values ('4205605','Galvão');",
    "Insert into cities (code, name) values ('4205704','Garopaba');",
    "Insert into cities (code, name) values ('4205803','Garuva');",
    "Insert into cities (code, name) values ('4205902','Gaspar');",
    "Insert into cities (code, name) values ('4206009','Governador Celso Ramos');",
    "Insert into cities (code, name) values ('4206108','Grão Pará');",
    "Insert into cities (code, name) values ('4206207','Gravatal');",
    "Insert into cities (code, name) values ('4206306','Guabiruba');",
    "Insert into cities (code, name) values ('4206405','Guaraciaba');",
    "Insert into cities (code, name) values ('4206504','Guaramirim');",
    "Insert into cities (code, name) values ('4206603','Guarujá do Sul');",
    "Insert into cities (code, name) values ('4206652','Guatambú');",
    "Insert into cities (code, name) values ('4206702','Herval D''Oeste');",
    "Insert into cities (code, name) values ('4206751','Ibiam');",
    "Insert into cities (code, name) values ('4206801','Ibicaré');",
    "Insert into cities (code, name) values ('4206900','Ibirama');",
    "Insert into cities (code, name) values ('4207007','Içara');",
    "Insert into cities (code, name) values ('4207106','Ilhota');",
    "Insert into cities (code, name) values ('4207205','Imaruí');",
    "Insert into cities (code, name) values ('4207304','Imbituba');",
    "Insert into cities (code, name) values ('4207403','Imbuia');",
    "Insert into cities (code, name) values ('4207502','Indaial');",
    "Insert into cities (code, name) values ('4207577','Iomerê');",
    "Insert into cities (code, name) values ('4207601','Ipira');",
    "Insert into cities (code, name) values ('4207650','Iporã do Oeste');",
    "Insert into cities (code, name) values ('4207684','Ipuaçu');",
    "Insert into cities (code, name) values ('4207700','Ipumirim');",
    "Insert into cities (code, name) values ('4207759','Iraceminha');",
    "Insert into cities (code, name) values ('4207809','Irani');",
    "Insert into cities (code, name) values ('4207858','Irati');",
    "Insert into cities (code, name) values ('4207908','Irineópolis');",
    "Insert into cities (code, name) values ('4208005','Itá');",
    "Insert into cities (code, name) values ('4208104','Itaiópolis');",
    "Insert into cities (code, name) values ('4208203','Itajaí');",
    "Insert into cities (code, name) values ('4208302','Itapema');",
    "Insert into cities (code, name) values ('4208401','Itapiranga');",
    "Insert into cities (code, name) values ('4208450','Itapoá');",
    "Insert into cities (code, name) values ('4208500','Ituporanga');",
    "Insert into cities (code, name) values ('4208609','Jaborá');",
    "Insert into cities (code, name) values ('4208708','Jacinto Machado');",
    "Insert into cities (code, name) values ('4208807','Jaguaruna');",
    "Insert into cities (code, name) values ('4208906','Jaraguá do Sul');",
    "Insert into cities (code, name) values ('4208955','Jardinópolis');",
    "Insert into cities (code, name) values ('4209003','Joaçaba');",
    "Insert into cities (code, name) values ('4209102','Joinville');",
    "Insert into cities (code, name) values ('4209151','José Boiteux');",
    "Insert into cities (code, name) values ('4209177','Jupiá');",
    "Insert into cities (code, name) values ('4209201','Lacerdópolis');",
    "Insert into cities (code, name) values ('4209300','Lages');",
    "Insert into cities (code, name) values ('4209409','Laguna');",
    "Insert into cities (code, name) values ('4209458','Lajeado Grande');",
    "Insert into cities (code, name) values ('4209508','Laurentino');",
    "Insert into cities (code, name) values ('4209607','Lauro Muller');",
    "Insert into cities (code, name) values ('4209706','Lebon Régis');",
    "Insert into cities (code, name) values ('4209805','Leoberto Leal');",
    "Insert into cities (code, name) values ('4209854','Lindóia do Sul');",
    "Insert into cities (code, name) values ('4209904','Lontras');",
    "Insert into cities (code, name) values ('4210001','Luiz Alves');",
    "Insert into cities (code, name) values ('4210035','Luzerna');",
    "Insert into cities (code, name) values ('4210050','Macieira');",
    "Insert into cities (code, name) values ('4210100','Mafra');",
    "Insert into cities (code, name) values ('4210209','Major Gercino');",
    "Insert into cities (code, name) values ('4210308','Major Vieira');",
    "Insert into cities (code, name) values ('4210407','Maracajá');",
    "Insert into cities (code, name) values ('4210506','Maravilha');",
    "Insert into cities (code, name) values ('4210555','Marema');",
    "Insert into cities (code, name) values ('4210605','Massaranduba');",
    "Insert into cities (code, name) values ('4210704','Matos Costa');",
    "Insert into cities (code, name) values ('4210803','Meleiro');",
    "Insert into cities (code, name) values ('4210852','Mirim Doce');",
    "Insert into cities (code, name) values ('4210902','Modelo');",
    "Insert into cities (code, name) values ('4211009','Mondaí');",
    "Insert into cities (code, name) values ('4211058','Monte Carlo');",
    "Insert into cities (code, name) values ('4211108','Monte Castelo');",
    "Insert into cities (code, name) values ('4211207','Morro da Fumaça');",
    "Insert into cities (code, name) values ('4211256','Morro Grande');",
    "Insert into cities (code, name) values ('4211306','Navegantes');",
    "Insert into cities (code, name) values ('4211405','Nova Erechim');",
    "Insert into cities (code, name) values ('4211454','Nova Itaberaba');",
    "Insert into cities (code, name) values ('4211504','Nova Trento');",
    "Insert into cities (code, name) values ('4211603','Nova Veneza');",
    "Insert into cities (code, name) values ('4211652','Novo Horizonte');",
    "Insert into cities (code, name) values ('4211702','Orleans');",
    "Insert into cities (code, name) values ('4211751','Otacílio Costa');",
    "Insert into cities (code, name) values ('4211801','Ouro');",
    "Insert into cities (code, name) values ('4211850','Ouro Verde');",
    "Insert into cities (code, name) values ('4211876','Paial');",
    "Insert into cities (code, name) values ('4211892','Painel');",
    "Insert into cities (code, name) values ('4211900','Palhoça');",
    "Insert into cities (code, name) values ('4212007','Palma Sola');",
    "Insert into cities (code, name) values ('4212056','Palmeira');",
    "Insert into cities (code, name) values ('4212106','Palmitos');",
    "Insert into cities (code, name) values ('4212205','Papanduva');",
    "Insert into cities (code, name) values ('4212239','Paraíso');",
    "Insert into cities (code, name) values ('4212254','Passo de Torres');",
    "Insert into cities (code, name) values ('4212270','Passos Maia');",
    "Insert into cities (code, name) values ('4212304','Paulo Lopes');",
    "Insert into cities (code, name) values ('4212403','Pedras Grandes');",
    "Insert into cities (code, name) values ('4212502','Penha');",
    "Insert into cities (code, name) values ('4212601','Peritiba');",
    "Insert into cities (code, name) values ('4212650','Pescaria Brava');",
    "Insert into cities (code, name) values ('4212700','Petrolândia');",
    "Insert into cities (code, name) values ('4212809','Balneário Piçarras');",
    "Insert into cities (code, name) values ('4212908','Pinhalzinho');",
    "Insert into cities (code, name) values ('4213005','Pinheiro Preto');",
    "Insert into cities (code, name) values ('4213104','Piratuba');",
    "Insert into cities (code, name) values ('4213153','Planalto Alegre');",
    "Insert into cities (code, name) values ('4213203','Pomerode');",
    "Insert into cities (code, name) values ('4213302','Ponte Alta');",
    "Insert into cities (code, name) values ('4213351','Ponte Alta do Norte');",
    "Insert into cities (code, name) values ('4213401','Ponte Serrada');",
    "Insert into cities (code, name) values ('4213500','Porto Belo');",
    "Insert into cities (code, name) values ('4213609','Porto União');",
    "Insert into cities (code, name) values ('4213708','Pouso Redondo');",
    "Insert into cities (code, name) values ('4213807','Praia Grande');",
    "Insert into cities (code, name) values ('4213906','Presidente Castello Branco');",
    "Insert into cities (code, name) values ('4214003','Presidente Getúlio');",
    "Insert into cities (code, name) values ('4214102','Presidente Nereu');",
    "Insert into cities (code, name) values ('4214151','Princesa');",
    "Insert into cities (code, name) values ('4214201','Quilombo');",
    "Insert into cities (code, name) values ('4214300','Rancho Queimado');",
    "Insert into cities (code, name) values ('4214409','Rio das Antas');",
    "Insert into cities (code, name) values ('4214508','Rio do Campo');",
    "Insert into cities (code, name) values ('4214607','Rio do Oeste');",
    "Insert into cities (code, name) values ('4214706','Rio dos Cedros');",
    "Insert into cities (code, name) values ('4214805','Rio do Sul');",
    "Insert into cities (code, name) values ('4214904','Rio Fortuna');",
    "Insert into cities (code, name) values ('4215000','Rio Negrinho');",
    "Insert into cities (code, name) values ('4215059','Rio Rufino');",
    "Insert into cities (code, name) values ('4215075','Riqueza');",
    "Insert into cities (code, name) values ('4215109','Rodeio');",
    "Insert into cities (code, name) values ('4215208','Romelândia');",
    "Insert into cities (code, name) values ('4215307','Salete');",
    "Insert into cities (code, name) values ('4215356','Saltinho');",
    "Insert into cities (code, name) values ('4215406','Salto Veloso');",
    "Insert into cities (code, name) values ('4215455','Sangão');",
    "Insert into cities (code, name) values ('4215505','Santa Cecília');",
    "Insert into cities (code, name) values ('4215554','Santa Helena');",
    "Insert into cities (code, name) values ('4215604','Santa Rosa de Lima');",
    "Insert into cities (code, name) values ('4215653','Santa Rosa do Sul');",
    "Insert into cities (code, name) values ('4215679','Santa Terezinha');",
    "Insert into cities (code, name) values ('4215687','Santa Terezinha do Progresso');",
    "Insert into cities (code, name) values ('4215695','Santiago do Sul');",
    "Insert into cities (code, name) values ('4215703','Santo Amaro da Imperatriz');",
    "Insert into cities (code, name) values ('4215752','São Bernardino');",
    "Insert into cities (code, name) values ('4215802','São Bento do Sul');",
    "Insert into cities (code, name) values ('4215901','São Bonifácio');",
    "Insert into cities (code, name) values ('4216008','São Carlos');",
    "Insert into cities (code, name) values ('4216057','São Cristovão do Sul');",
    "Insert into cities (code, name) values ('4216107','São Domingos');",
    "Insert into cities (code, name) values ('4216206','São Francisco do Sul');",
    "Insert into cities (code, name) values ('4216255','São João do Oeste');",
    "Insert into cities (code, name) values ('4216305','São João Batista');",
    "Insert into cities (code, name) values ('4216354','São João do Itaperiú');",
    "Insert into cities (code, name) values ('4216404','São João do Sul');",
    "Insert into cities (code, name) values ('4216503','São Joaquim');",
    "Insert into cities (code, name) values ('4216602','São José');",
    "Insert into cities (code, name) values ('4216701','São José do Cedro');",
    "Insert into cities (code, name) values ('4216800','São José do Cerrito');",
    "Insert into cities (code, name) values ('4216909','São Lourenço do Oeste');",
    "Insert into cities (code, name) values ('4217006','São Ludgero');",
    "Insert into cities (code, name) values ('4217105','São Martinho');",
    "Insert into cities (code, name) values ('4217154','São Miguel da Boa Vista');",
    "Insert into cities (code, name) values ('4217204','São Miguel do Oeste');",
    "Insert into cities (code, name) values ('4217253','São Pedro de Alcântara');",
    "Insert into cities (code, name) values ('4217303','Saudades');",
    "Insert into cities (code, name) values ('4217402','Schroeder');",
    "Insert into cities (code, name) values ('4217501','Seara');",
    "Insert into cities (code, name) values ('4217550','Serra Alta');",
    "Insert into cities (code, name) values ('4217600','Siderópolis');",
    "Insert into cities (code, name) values ('4217709','Sombrio');",
    "Insert into cities (code, name) values ('4217758','Sul Brasil');",
    "Insert into cities (code, name) values ('4217808','Taió');",
    "Insert into cities (code, name) values ('4217907','Tangará');",
    "Insert into cities (code, name) values ('4217956','Tigrinhos');",
    "Insert into cities (code, name) values ('4218004','Tijucas');",
    "Insert into cities (code, name) values ('4218103','Timbé do Sul');",
    "Insert into cities (code, name) values ('4218202','Timbó');",
    "Insert into cities (code, name) values ('4218251','Timbó Grande');",
    "Insert into cities (code, name) values ('4218301','Três Barras');",
    "Insert into cities (code, name) values ('4218350','Treviso');",
    "Insert into cities (code, name) values ('4218400','Treze de Maio');",
    "Insert into cities (code, name) values ('4218509','Treze Tílias');",
    "Insert into cities (code, name) values ('4218608','Trombudo Central');",
    "Insert into cities (code, name) values ('4218707','Tubarão');",
    "Insert into cities (code, name) values ('4218756','Tunápolis');",
    "Insert into cities (code, name) values ('4218806','Turvo');",
    "Insert into cities (code, name) values ('4218855','União do Oeste');",
    "Insert into cities (code, name) values ('4218905','Urubici');",
    "Insert into cities (code, name) values ('4218954','Urupema');",
    "Insert into cities (code, name) values ('4219002','Urussanga');",
    "Insert into cities (code, name) values ('4219101','Vargeão');",
    "Insert into cities (code, name) values ('4219150','Vargem');",
    "Insert into cities (code, name) values ('4219176','Vargem Bonita');",
    "Insert into cities (code, name) values ('4219200','Vidal Ramos');",
    "Insert into cities (code, name) values ('4219309','Videira');",
    "Insert into cities (code, name) values ('4219358','Vitor Meireles');",
    "Insert into cities (code, name) values ('4219408','Witmarsum');",
    "Insert into cities (code, name) values ('4219507','Xanxerê');",
    "Insert into cities (code, name) values ('4219606','Xavantina');",
    "Insert into cities (code, name) values ('4219705','Xaxim');",
    "Insert into cities (code, name) values ('4219853','Zortéa');",
    "Insert into cities (code, name) values ('4220000','Balneário Rincão');"
]